// This file will be auto-generated by Supabase CLI
// For now, we'll create a basic structure that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          first_name: string
          last_name: string
          phone_number: string | null
          avatar: string | null
          role: 'admin' | 'supplier' | 'couple' | 'guest'
          status: 'active' | 'inactive' | 'suspended' | 'pending'
          last_login_at: string | null
          email_verified_at: string | null
          phone_verified_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          first_name: string
          last_name: string
          phone_number?: string | null
          avatar?: string | null
          role?: 'admin' | 'supplier' | 'couple' | 'guest'
          status?: 'active' | 'inactive' | 'suspended' | 'pending'
          last_login_at?: string | null
          email_verified_at?: string | null
          phone_verified_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          first_name?: string
          last_name?: string
          phone_number?: string | null
          avatar?: string | null
          role?: 'admin' | 'supplier' | 'couple' | 'guest'
          status?: 'active' | 'inactive' | 'suspended' | 'pending'
          last_login_at?: string | null
          email_verified_at?: string | null
          phone_verified_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      supplier_profiles: {
        Row: {
          id: string
          user_id: string
          business_name: string
          specialization: 'photographer' | 'videographer' | 'caterer' | 'florist' | 'venue' | 'dj' | 'band' | 'planner' | 'decorator' | 'transportation' | 'other'
          description: string | null
          website: string | null
          logo: string | null
          street: string | null
          city: string | null
          state: string | null
          postal_code: string | null
          country: string | null
          latitude: number | null
          longitude: number | null
          subscription_tier: 'free' | 'starter' | 'professional' | 'scale' | 'enterprise'
          subscription_expires_at: string | null
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          business_name: string
          specialization: 'photographer' | 'videographer' | 'caterer' | 'florist' | 'venue' | 'dj' | 'band' | 'planner' | 'decorator' | 'transportation' | 'other'
          description?: string | null
          website?: string | null
          logo?: string | null
          street?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string | null
          latitude?: number | null
          longitude?: number | null
          subscription_tier?: 'free' | 'starter' | 'professional' | 'scale' | 'enterprise'
          subscription_expires_at?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          business_name?: string
          specialization?: 'photographer' | 'videographer' | 'caterer' | 'florist' | 'venue' | 'dj' | 'band' | 'planner' | 'decorator' | 'transportation' | 'other'
          description?: string | null
          website?: string | null
          logo?: string | null
          street?: string | null
          city?: string | null
          state?: string | null
          postal_code?: string | null
          country?: string | null
          latitude?: number | null
          longitude?: number | null
          subscription_tier?: 'free' | 'starter' | 'professional' | 'scale' | 'enterprise'
          subscription_expires_at?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "supplier_profiles_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      couple_profiles: {
        Row: {
          id: string
          partner_one_id: string
          partner_two_id: string
          relationship_status: string
          shared_email: string | null
          preferences: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          partner_one_id: string
          partner_two_id: string
          relationship_status?: string
          shared_email?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          partner_one_id?: string
          partner_two_id?: string
          relationship_status?: string
          shared_email?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "couple_profiles_partner_one_id_fkey"
            columns: ["partner_one_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "couple_profiles_partner_two_id_fkey"
            columns: ["partner_two_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      weddings: {
        Row: {
          id: string
          couple_id: string
          wedding_date: string
          ceremony_venue: Json | null
          reception_venue: Json | null
          guest_count: number
          estimated_budget: number | null
          actual_budget: number | null
          theme: string | null
          color_scheme: string[] | null
          status: 'planning' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'postponed'
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          couple_id: string
          wedding_date: string
          ceremony_venue?: Json | null
          reception_venue?: Json | null
          guest_count?: number
          estimated_budget?: number | null
          actual_budget?: number | null
          theme?: string | null
          color_scheme?: string[] | null
          status?: 'planning' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'postponed'
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          couple_id?: string
          wedding_date?: string
          ceremony_venue?: Json | null
          reception_venue?: Json | null
          guest_count?: number
          estimated_budget?: number | null
          actual_budget?: number | null
          theme?: string | null
          color_scheme?: string[] | null
          status?: 'planning' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'postponed'
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "weddings_couple_id_fkey"
            columns: ["couple_id"]
            referencedRelation: "couple_profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      guests: {
        Row: {
          id: string
          wedding_id: string
          first_name: string
          last_name: string
          email: string | null
          phone_number: string | null
          address: Json | null
          relationship: string
          is_child: boolean
          dietary_requirements: Json
          rsvp_status: 'pending' | 'accepted' | 'declined' | 'maybe'
          rsvp_date: string | null
          plus_one_allowed: boolean
          plus_one_details: Json | null
          photo_group: string | null
          table_assignment: string | null
          notes: string | null
          invitation_sent_at: string | null
          reminder_sent_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          first_name: string
          last_name: string
          email?: string | null
          phone_number?: string | null
          address?: Json | null
          relationship: string
          is_child?: boolean
          dietary_requirements?: Json
          rsvp_status?: 'pending' | 'accepted' | 'declined' | 'maybe'
          rsvp_date?: string | null
          plus_one_allowed?: boolean
          plus_one_details?: Json | null
          photo_group?: string | null
          table_assignment?: string | null
          notes?: string | null
          invitation_sent_at?: string | null
          reminder_sent_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          first_name?: string
          last_name?: string
          email?: string | null
          phone_number?: string | null
          address?: Json | null
          relationship?: string
          is_child?: boolean
          dietary_requirements?: Json
          rsvp_status?: 'pending' | 'accepted' | 'declined' | 'maybe'
          rsvp_date?: string | null
          plus_one_allowed?: boolean
          plus_one_details?: Json | null
          photo_group?: string | null
          table_assignment?: string | null
          notes?: string | null
          invitation_sent_at?: string | null
          reminder_sent_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "guests_wedding_id_fkey"
            columns: ["wedding_id"]
            referencedRelation: "weddings"
            referencedColumns: ["id"]
          }
        ]
      }
      forms: {
        Row: {
          id: string
          supplier_id: string
          name: string
          description: string | null
          version: number
          status: 'draft' | 'published' | 'archived'
          fields: Json
          logic: Json
          branding: Json
          settings: Json
          analytics: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          supplier_id: string
          name: string
          description?: string | null
          version?: number
          status?: 'draft' | 'published' | 'archived'
          fields?: Json
          logic?: Json
          branding?: Json
          settings?: Json
          analytics?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          supplier_id?: string
          name?: string
          description?: string | null
          version?: number
          status?: 'draft' | 'published' | 'archived'
          fields?: Json
          logic?: Json
          branding?: Json
          settings?: Json
          analytics?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "forms_supplier_id_fkey"
            columns: ["supplier_id"]
            referencedRelation: "supplier_profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      journeys: {
        Row: {
          id: string
          supplier_id: string
          name: string
          description: string | null
          status: 'draft' | 'active' | 'paused' | 'archived'
          trigger: Json
          nodes: Json
          connections: Json
          settings: Json
          analytics: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          supplier_id: string
          name: string
          description?: string | null
          status?: 'draft' | 'active' | 'paused' | 'archived'
          trigger: Json
          nodes?: Json
          connections?: Json
          settings?: Json
          analytics?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          supplier_id?: string
          name?: string
          description?: string | null
          status?: 'draft' | 'active' | 'paused' | 'archived'
          trigger?: Json
          nodes?: Json
          connections?: Json
          settings?: Json
          analytics?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "journeys_supplier_id_fkey"
            columns: ["supplier_id"]
            referencedRelation: "supplier_profiles"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'admin' | 'supplier' | 'couple' | 'guest'
      user_status: 'active' | 'inactive' | 'suspended' | 'pending'
      subscription_tier: 'free' | 'starter' | 'professional' | 'scale' | 'enterprise'
      supplier_specialization: 'photographer' | 'videographer' | 'caterer' | 'florist' | 'venue' | 'dj' | 'band' | 'planner' | 'decorator' | 'transportation' | 'other'
      wedding_status: 'planning' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'postponed'
      rsvp_status: 'pending' | 'accepted' | 'declined' | 'maybe'
      form_status: 'draft' | 'published' | 'archived'
      journey_status: 'draft' | 'active' | 'paused' | 'archived'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}